export { default as Hero } from "./Hero"
export { default as Service } from "./Service"
export { default as WhyUs } from "./WhyUs"
export { default as Testimonial } from "./Testimonial"
export { default as CtaBanner } from "./CtaBanner"
export { default as Faq } from "./Faq"
